[project]
name = "pag-runs-processing"
version = "0.1.0"
description = "UV Implementation of Vivek's environment"
readme = "README.md"
requires-python = "==3.9.6"
dependencies = [
    "anywidget==0.9.18",
    "emat>=0.6.0",
    "numpy==1.23.5",
    "openpyxl==3.1.5",
    "pandas==1.3.5",
    "pyarrow==15.0.1",
    "scikit-learn==1.1.3",
    "statsmodels==0.13.5",
]
